name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Test
      run: swift test

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.10", "5.9", "5.8", "5.7"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Test
      run: swift test
